# Generated by Django 5.2.11 on 2026-03-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannedin', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('other', 'Other (Personal use)')], max_length=20),
        ),
    ]
