# Generated by Django 5.2.11 on 2026-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannedin', '0004_attendancesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='class_name',
            field=models.CharField(default='Class 1', max_length=120),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='course_name',
            field=models.CharField(default='General Course', max_length=120),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
